name: Autograding Tests

on:
  push: {}
  repository_dispatch: {}

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    name: Run Autograding Tests
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run Python Grader
        id: tests
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: "python -m pytest tests/ -q --disable-warnings --maxfail=1"
          setup-command: ""
          timeout: 600   # 10 minutes in seconds
          max-score: 100

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TESTS_RESULTS: ${{ steps.tests.outputs.result }}
        with:
          runners: tests
